import type { Metadata } from 'next';
import theme from '@/theme';
import { ThemeProvider } from '@mui/material';
import Footer from './components/footer';
import Navbar from './components/navbar';
import './styles/globals.css';

export const metadata: Metadata = {
  title: 'Crypto Wizard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ThemeProvider>
  );
}
