import img1 from '../../../../../public/images/spotlight-cards/1.png';
import img2 from '../../../../../public/images/spotlight-cards/2.png';
import score from '../../../../../public/images/spotlight-cards/score.png';
import graph from '../../../../../public/images/spotlight-cards/Frame.png';

export const spotlightCardData = [
  {
    id: '1',
    img: img1,
    background: '/images/spotlight-cards/background1.png',
    title: 'Bitcoin',
    subtitle: 'BTC',
    score: score,
    price: '$49,627.43',
    change: '+7.37%',
    marketCap: '$49,627M',
    circulationSupply: '19.63M (93.46%)',
    volume: '$33.96B',
    totalMaxSupply: '21.00M',
    graph: graph,
  },
  {
    id: '2',
    img: img2,
    background: '/images/spotlight-cards/background1.png',
    title: 'Ethereum',
    subtitle: 'ETH',
    score: score,
    price: '$4,232.19',
    change: '-5.22%',
    marketCap: '$25,367M',
    circulationSupply: '114.45M (91.23%)',
    volume: '$15.36B',
    totalMaxSupply: 'N/A',
    graph: graph,
  },
  {
    id: '3',
    img: img2,
    background: '/images/spotlight-cards/background2.png',
    title: 'Ethereum',
    subtitle: 'ETH',
    score: score,
    price: '$4,232.19',
    change: '+5.22%',
    marketCap: '$25,367M',
    circulationSupply: '114.45M (91.23%)',
    volume: '$15.36B',
    totalMaxSupply: 'N/A',
    graph: graph,
  },
  {
    id: '4',
    img: img2,
    background: '/images/spotlight-cards/background1.png',
    title: 'Ethereum',
    subtitle: 'ETH',
    score: score,
    price: '$4,232.19',
    change: '-5.22%',
    marketCap: '$25,367M',
    circulationSupply: '114.45M (91.23%)',
    volume: '$15.36B',
    totalMaxSupply: 'N/A',
    graph: graph,
  },
  {
    id: '5',
    img: img2,
    background: '/images/spotlight-cards/background2.png',
    title: 'Ethereum',
    subtitle: 'ETH',
    score: score,
    price: '$4,232.19',
    change: '-5.22%',
    marketCap: '$25,367M',
    circulationSupply: '114.45M (91.23%)',
    volume: '$15.36B',
    totalMaxSupply: 'N/A',
    graph: graph,
  },
  {
    id: '6',
    img: img2,
    background: '/images/spotlight-cards/background2.png',
    title: 'Ethereum',
    subtitle: 'ETH',
    score: score,
    price: '$4,232.19',
    change: '+5.22%',
    marketCap: '$25,367M',
    circulationSupply: '114.45M (91.23%)',
    volume: '$15.36B',
    totalMaxSupply: 'N/A',
    graph: graph,
  },
];
